"""One-page ATS-friendly Typst PDF rendering with automatic trimming."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from copy import deepcopy
from pathlib import Path
from typing import Any

from pypdf import PdfReader

from .render import _format_date_range, _resume_sections
from .assembly import apply_assembly, build_assembly


TYPST_VERSION = "0.15.1"


def typst_binary(explicit_path: str | Path | None = None) -> Path:
    """Resolve a local Typst binary without silently choosing another renderer."""
    candidates: list[Path]
    if explicit_path is not None:
        candidates = [Path(explicit_path)]
    elif os.environ.get("TYPST_BIN"):
        candidates = [Path(os.environ["TYPST_BIN"])]
    else:
        root = Path(__file__).resolve().parents[1]
        candidates = [root / ".venv" / "bin" / "typst", Path("typst")]
    for candidate in candidates:
        if candidate.is_absolute() and candidate.is_file():
            return candidate
        resolved = shutil.which(str(candidate))
        if resolved:
            return Path(resolved)
    raise RuntimeError(
        "Typst was not found. Run scripts/install-typst.sh or set TYPST_BIN."
    )


def _json_string(value: Any) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _typst_content(value: Any) -> str:
    """Escape untrusted text for a Typst content block."""
    text = str(value)
    replacements = {
        "\\": "\\\\",
        "#": "\\#",
        "[": "\\[",
        "]": "\\]",
        "*": "\\*",
        "_": "\\_",
        "`": "\\`",
        "$": "\\$",
        "<": "\\<",
        ">": "\\>",
        "@": "\\@",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return f"[{text}]"


def render_resume_typst(
    plan: dict[str, Any],
    profile: dict[str, Any],
    *,
    summary: str | None = None,
) -> str:
    """Render a single-column Typst resume from validated reviewed evidence."""
    resume = _resume_sections(plan, profile, summary=summary)
    contact = resume["contact"]
    links = contact["links"]

    lines = [
        f"// Generated by resume-god with Typst {TYPST_VERSION}",
        '#set page(paper: "a4", margin: (x: 1.35cm, y: 1.0cm), numbering: none)',
        '#set text(font: "New Computer Modern", size: 9.1pt, lang: "en", fill: black)',
        "#set par(leading: 0.42em, first-line-indent: 0em, justify: false)",
        "#set list(tight: true, indent: 0.75em, spacing: 0.28em)",
        "#let section(title) = block(above: 7pt, below: 3pt, {",
        "  text(size: 9.3pt, weight: \"bold\", style: \"normal\", upper(title))",
        "  v(-5pt)",
        "  line(length: 100%, stroke: 0.55pt + black)",
        "})",
        "#let entry-heading(title, details) = grid(",
        "  columns: (1fr, auto),",
        "  align: (left, right),",
        "  text(size: 9.5pt, weight: \"bold\", title),",
        "  text(size: 8.4pt, fill: rgb(\"#374151\"), details),",
        ")",
        "#align(center, text(size: 18.5pt, weight: \"bold\", " + _typst_content(contact["name"]) + "))",
        "#align(center, text(size: 10.4pt, fill: rgb(\"#374151\"), " + _typst_content(resume["target_title"]) + "))",
    ]
    contact_bits = [contact["location"], contact["phone"], contact["email"]]
    contact_values = [_typst_content(item) for item in contact_bits if item]
    lines.append(
        "#align(center, text(size: 8.2pt, {"
        + " + [ · ] + ".join(contact_values)
        + "}))"
    )
    link_values = [
        f"link({_json_string(link['url'])}){_typst_content(link['label'])}"
        for link in links
    ]
    lines.append(
        "#align(center, text(size: 8.2pt, {"
        + " + [ · ] + ".join(link_values)
        + "}))"
    )
    lines.extend(
        [
            f"#section{_typst_content('Professional Summary')}",
            f"#text{_typst_content(resume['summary'])}",
            f"#section{_typst_content('Skills')}",
        ]
    )

    categories: dict[str, list[str]] = {}
    for skill in resume["skills"]:
        categories.setdefault(skill["category"], []).append(skill["name"])
    for category, names in categories.items():
        lines.append(
            f"#text(weight: \"bold\"){_typst_content(category + ':')} "
            f"#text{_typst_content(', '.join(names))}"
        )

    section_order = plan.get("assembly", {}).get(
        "section_order", ["experience", "project"]
    )
    headings = {
        "experience": "Relevant Experience",
        "project": "Selected Projects",
    }
    for kind in section_order:
        matching = [item for item in resume["selected_parents"] if item["kind"] == kind]
        if not matching:
            continue
        lines.append(f"#section{_typst_content(headings[kind])}")
        for parent in matching:
            node = parent["node"]
            if parent["kind"] == "experience":
                title = f"{node['role']} — {node['organization']}"
            else:
                title = (
                    node["name"]
                    if node.get("name") == node.get("title")
                    else f"{node['name']} — {node['title']}"
                )
            details = " · ".join(
                item for item in (parent.get("date_range"), node.get("location") or node.get("url")) if item
            )
            lines.append(f"#entry-heading{_typst_content(title)}{_typst_content(details)}")
            for bullet in parent["achievements"]:
                lines.append(f"- #text{_typst_content(bullet)}")

    lines.append(f"#section{_typst_content('Education')}")
    for node in resume["education"]:
        details = " · ".join(
            item
            for item in (
                node.get("location"),
                _format_date_range(node.get("date_range")),
                f"CGPA: {node['cgpa']}" if node.get("cgpa") else None,
            )
            if item
        )
        lines.append(
            f"#entry-heading{_typst_content(node['credential'] + ' — ' + node['institution'])}{_typst_content(details)}"
        )
        if node.get("coursework"):
            lines.append(
                f"#text(size: 8.2pt){_typst_content('Coursework: ' + ', '.join(node['coursework']))}"
            )

    if resume["certifications"]:
        lines.append(f"#section{_typst_content('Certifications')}")
        for node in resume["certifications"]:
            lines.append(
                f"- #text{_typst_content(node['name'] + ' — ' + node['issuer'] + ' (' + node['issued_on'] + ')')}"
            )

    return "\n".join(lines) + "\n"


def _pdf_page_count(path: Path) -> int:
    return len(PdfReader(str(path)).pages)


def _update_coverage_after_trim(
    plan: dict[str, Any], profile: dict[str, Any]
) -> None:
    selected_ids = {item["id"] for item in plan["selected_achievements"]}
    selected_skills = {
        skill_id
        for achievement in plan["selected_achievements"]
        for skill_id in achievement["skills"]
    }
    available = {
        skill_id
        for achievement in profile["achievements"]
        for skill_id in achievement["skills"]
    }
    profile_skill_ids = {item["id"] for item in profile["skills"]}
    for row in plan.get("requirement_coverage", []):
        if row["kind"] != "profile_skill":
            continue
        if row["id"] in selected_skills:
            row["status"] = "covered"
            row["evidence_available"] = True
        elif row["id"] in available:
            row["status"] = "profile_skill_not_selected"
            row["evidence_available"] = True
        else:
            row["status"] = "profile_skill_without_evidence"
            row["evidence_available"] = False
    plan["gap_report"]["matched_but_unevidenced_skills"] = [
        {
            "id": row["id"],
            "name": row["name"],
            "priority": row["priority"],
            "status": row["status"],
        }
        for row in plan.get("requirement_coverage", [])
        if row["kind"] == "profile_skill"
        and row["status"] != "covered"
        and row["id"] in profile_skill_ids
    ]
    plan["gap_report"]["all_known_requirements_covered"] = not plan["gap_report"][
        "matched_but_unevidenced_skills"
    ]


def _without_lowest_ranked(
    plan: dict[str, Any], profile: dict[str, Any], *, summary: str | None
) -> dict[str, Any]:
    ranking = list(plan.get("ranking", []))
    if len(ranking) <= 1:
        raise ValueError("Resume still exceeds one page after retaining the top bullet")
    ranking.pop()
    base = deepcopy(plan)
    base["ranking"] = ranking
    achievements = {item["id"]: item for item in profile["achievements"]}
    retained_ids = {row["achievement_id"] for row in ranking}
    base["selected_achievements"] = [
        achievements[item] for item in retained_ids
    ]
    base.pop("assembly", None)
    assembly = build_assembly(
        base,
        profile,
        page_budget_chars=10_000_000,
        summary=summary,
    )
    result = apply_assembly(base, profile, assembly)
    result["rewrites"] = {
        achievement_id: record
        for achievement_id, record in plan.get("rewrites", {}).items()
        if achievement_id in retained_ids
    }
    used = sum(record["used_rewrite"] for record in result["rewrites"].values())
    result["rewrite_summary"] = {
        "selected_achievement_count": len(result["rewrites"]),
        "used_rewrite_count": used,
        "fallback_count": len(result["rewrites"]) - used,
    }
    _update_coverage_after_trim(result, profile)
    return result


def write_resume_pdf(
    plan: dict[str, Any],
    profile: dict[str, Any],
    output_path: str | Path,
    *,
    summary: str | None = None,
    typst_path: str | Path | None = None,
    keep_source_path: str | Path | None = None,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Compile repeatedly, removing the lowest-ranked bullet if pages spill."""
    binary = typst_binary(typst_path)
    version = subprocess.run(
        [str(binary), "--version"], check=True, capture_output=True, text=True
    ).stdout.strip().removeprefix("typst ")
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    current = deepcopy(plan)
    trimmed: list[str] = []
    with tempfile.TemporaryDirectory(prefix="resume-god-typst-") as directory:
        temporary = Path(directory)
        source_path = temporary / "resume.typ"
        pdf_path = temporary / "resume.pdf"
        attempts: list[dict[str, Any]] = []

        while True:
            source = render_resume_typst(current, profile, summary=summary)
            source_path.write_text(source, encoding="utf-8")
            compiled = subprocess.run(
                [str(binary), "compile", str(source_path), str(pdf_path)],
                capture_output=True,
                text=True,
            )
            if compiled.returncode != 0:
                raise RuntimeError(
                    "Typst compilation failed:\n" + compiled.stdout + compiled.stderr
                )
            pages = _pdf_page_count(pdf_path)
            attempts.append(
                {
                    "achievement_count": len(current["selected_achievements"]),
                    "page_count": pages,
                }
            )
            if pages == 1:
                if keep_source_path is not None:
                    keep = Path(keep_source_path)
                    keep.parent.mkdir(parents=True, exist_ok=True)
                    keep.write_text(source, encoding="utf-8")
                output.write_bytes(pdf_path.read_bytes())
                result = {
                    "output": str(output),
                    "renderer": "typst",
                    "renderer_version": f"Typst {version}",
                    "page_count": pages,
                    "attempts": attempts,
                    "trimmed_for_one_page": trimmed,
                    "audit_passed": all(current["audit"].values())
                    and all(current.get("rewrite_audit", {}).values()),
                }
                return current, result
            if len(current["selected_achievements"]) <= 1:
                raise RuntimeError(
                    "Even the highest-ranked bullet cannot fit on one page"
                )
            removed = current["ranking"][-1]["achievement_id"]
            trimmed.append(removed)
            current = _without_lowest_ranked(
                current, profile, summary=summary
            )
